services:
  postgres:
      image: postgres:15
          environment:
                POSTGRES_DB: ${DB_NAME}
                      POSTGRES_USER: ${DB_USER}
                            POSTGRES_PASSWORD: ${DB_PASSWORD}
                                ports:
                                      - "5432:5432"
                                        influxdb:
                                            image: influxdb:2.0
                                                ports:
                                                      - "8086:8086"
                                                        mosquitto:
                                                            image: eclipse-mosquitto
                                                                ports:
                                                                      - "1883:1883"
                                                                            - "9001:9001"
                                                                              zookeeper:
                                                                                  image: confluentinc/cp-zookeeper:latest
                                                                                      environment:
                                                                                            ZOOKEEPER_CLIENT_PORT: 2181
                                                                                              kafka:
                                                                                                  image: confluentinc/cp-kafka:latest
                                                                                                      depends_on:
                                                                                                            - zookeeper
                                                                                                                ports:
                                                                                                                      - "9092:9092"
                                                                                                                        nginx:
                                                                                                                            image: nginx:latest
                                                                                                                                ports:
                                                                                                                                      - "80:80"
                                                                                                                                          volumes:
                                                                                                                                                - ./nginx/conf.d:/etc/nginx/conf.d
