apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    password: ${INFLUX_TOKEN}
    user: admin
    database: habitat_sensors
    jsonData:
      version: Flux
      organization: imm_org
      defaultBucket: habitat_sensors
      tlsSkipVerify: true
    secureJsonData:
      token: ${INFLUX_TOKEN}
    isDefault: true
