[all:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=~/.ssh/imm_id_rsa
ansible_python_interpreter=/usr/bin/python3

[devserver]
# Replace with your dev server IP
devserver ansible_host=192.168.1.100

[rpis]
# Replace with your RPi IPs
rpi01 ansible_host=192.168.1.101
rpi02 ansible_host=192.168.1.102

[jetson]
# Replace with your Jetson IP
jetson01 ansible_host=192.168.1.103
